# Numpy Basics <hr style="border:2.5px solid #FF69B4 "></hr>

Data Analyst: Rosemae A. Samillano <br>
Department: Electrical Engineering

In [3]:
# imports and packages
import numpy as np
from scipy import stats

# 1D Array

In [7]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

# 2D Array

In [14]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
my_array = my_array.T
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
np.sum(my_array, axis = 0)

array([ 6, 15])

In [17]:
np.sum(my_array, axis = 1)

array([5, 7, 9])

# Measures of Central Tendency

In [4]:
 fruits = np.array([120,60,85,150,200])

In [5]:
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [6]:
median_fruits = np.median(fruits)
median_fruits

np.float64(120.0)

In [19]:
mode_fruits = stats.mode(fruits)
mode_fruits
print(" The mode is " + str(mode_fruits))

 The mode is ModeResult(mode=np.int64(60), count=np.int64(1))


# Jaquar vs Panther

## Jaquar

In [20]:
jaquar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaquar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [24]:
jaquar_mean = np.mean(jaquar)
jaquar_mean
print( "The mean is " + str(jaquar_mean))

The mean is 9.399999999999999


In [26]:
jaquar_median = np.median(jaquar)
jaquar_median
print( "The median is " + str(jaquar_median))

The median is 9.8


In [29]:
jaquar_mode = stats.mode(jaquar)
jaquar_mode
print( "The mode is " + str(jaquar_mode))

The mode is ModeResult(mode=np.float64(9.8), count=np.int64(2))


In [30]:
max_jaquar = np.max(jaquar)
min_jaquar = np.min(jaquar)

range_jaquar = max_jaquar - min_jaquar
range_jaquar
print( "The range is " + str(range_jaquar))

The range is 8.0


In [31]:
q1_jaquar = np.percentile(jaquar,25)
q1_jaquar
print( "The 1st quartile is " + str(q1_jaquar))

The 1st quartile is 9.4


In [32]:
q2_jaquar = np.percentile(jaquar,50)
q2_jaquar
print( "The 2nd percentile is " + str(q2_jaquar))

The 2nd percentile is 9.8


In [33]:
q3_jaquar = np.percentile(jaquar,75)
q3_jaquar
print( "The 3rd percentile is " + str(q3_jaquar))

The 3rd percentile is 10.45


In [34]:
iqr_jaquar = q3_jaquar - q1_jaquar
iqr_jaquar
print( "The iqr is " + str(iqr_jaquar))

The iqr is 1.049999999999999


In [36]:
var_jaquar = np.var(jaquar,ddof=1)
var_jaquar
print( "The variance is " + str(var_jaquar))

The variance is 4.86


In [37]:
samplestd_jaquar = np.std(jaquar,ddof=1)
samplestd_jaquar
print( "The sample standard deviation is " + str(samplestd_jaquar))

The sample standard deviation is 2.2045407685048604


## Panther 

In [39]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [41]:
panther_mean = np.mean(panther)
panther_mean
print("The mean is " + str(panther_mean))

The mean is 10.75


In [42]:
panther_median = np.median(panther)
panther_median 
print("The median is " + str(panther_median))

The median is 9.55


In [43]:
panther_mode = stats.mode(panther)
panther_mode
print("The mode is " + str(panther_mode))

The mode is ModeResult(mode=np.float64(9.1), count=np.int64(3))


In [45]:
max_panther = np.max(panther)
min_panther = np.min(panther)

range_panther = max_panther - min_panther
range_panther
print("The range is " + str(range_panther))

The range is 10.9


In [46]:
q1_panther = np.percentile(panther,25)
q1_panther
print( "The 1st percentile is " + str(q1_panther))

The 1st percentile is 9.125


In [48]:
q2_panther = np.percentile(panther,50)
q2_panther
print("The 2nd percentile is " + str(q2_panther))

The 2nd percentile is 9.55


In [49]:
q3_panther = np.percentile(panther,75)
q3_panther
print("The 3rd percentile is " + str(q3_panther))

The 3rd percentile is 10.625


In [50]:
iqr_panther = q3_panther - q1_panther
iqr_panther
print("The iqr is " + str(iqr_panther))

The iqr is 1.5


In [51]:
var_panther = np.var(panther,ddof=1)
var_panther
print("The variance is " + str(var_panther))

The variance is 11.082777777777777


In [52]:
samplestd_panther = np.std(panther,ddof=1)
samplestd_panther
print("The standard variance deviation is " + str(samplestd_panther))

The standard variance deviation is 3.3290806204983645
